spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bc14d26dfd4751:1a6fac4d@us-cdbr-east-06.cleardb.net/heroku_c049d90fa5c4ed3?reconnect=true
    username: bc14d26dfd4751
    password: 1a6fac4d
    hikari.maximum-pool-size: 4
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: project.sns-application-2023.secret_key
  #30일
  token.expired-time-ms: 2592000000